---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Fragment
metadata:
  name: boot-upgrade
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/trisberg/acc-day-2.git
    ref:
      branch: main
    subPath: fragments/boot-upgrade
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: hello-world
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/trisberg/acc-day-2.git
    ref:
      branch: main
    subPath: hello-world
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: hello-world-update
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/trisberg/acc-day-2.git
    ref:
      branch: main
    subPath: hello-world-update
